# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - 8ai-chatbot-backend

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "18.x" # set this to the node version to use (supports 8.x, 10.x, 12.x)
  NODE_ENV: "production"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: "Production"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Install"
        run: npm install

      - name: "Build"
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9B5540563F4644ACB31E7E63399AFC27 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8ABD951C49364F6AA7A33A4EFA534117 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DBED5655BD404C4BADE011F6E918BF2B }}

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "8ai-chatbot-backend"
          slot-name: "offline"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_STAGING }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
